[package]
name = "raytracer_shared"
version = "0.1.2"
authors = ["Michael Völkl<michaelvoelkl@zoho.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pkg-version = "1.0.0"
