[package]
name = "raytracer_plugin"
version = "0.1.0"
authors = ["Michael <v.mi@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
